//Vizsgált objektum:
let helsinki = [
    { helyezes: 1, csapatMeret: 1, sportag: "atletika", versenyszam: "kalapacsvetes" },
    { helyezes: 1, csapatMeret: 1, sportag: "uszas", versenyszam: "400m_gyorsuszas" },
    { helyezes: 1, csapatMeret: 1, sportag: "birkozas", versenyszam: "kotott_fogas_legsuly" },
    { helyezes: 1, csapatMeret: 1, sportag: "torna", versenyszam: "talajtorna" },
    { helyezes: 1, csapatMeret: 1, sportag: "torna", versenyszam: "felemas_korlat" },
    { helyezes: 1, csapatMeret: 1, sportag: "vivas", versenyszam: "kardvivas_egyeni" },
    { helyezes: 1, csapatMeret: 1, sportag: "okolvivas", versenyszam: "nagyvaltosuly" },
    { helyezes: 1, csapatMeret: 1, sportag: "uszas", versenyszam: "200m_melluszas" },
    { helyezes: 1, csapatMeret: 1, sportag: "birkozas", versenyszam: "kotott_fogas_valtosuly" },
    { helyezes: 1, csapatMeret: 1, sportag: "uszas", versenyszam: "100m_gyorsuszas" },
    { helyezes: 1, csapatMeret: 1, sportag: "sportloveszet", versenyszam: "onmukodo_sportpisztoly" },
    { helyezes: 1, csapatMeret: 15, sportag: "labdarugas", versenyszam: "ferfi_csapat" },
    { helyezes: 1, csapatMeret: 3, sportag: "ottusa", versenyszam: "ferfi_csapat" },
    { helyezes: 1, csapatMeret: 6, sportag: "vivas", versenyszam: "kardvivas_csapat" },
    { helyezes: 1, csapatMeret: 5, sportag: "uszas", versenyszam: "4x100m_gyorsuszo_valto" },
    { helyezes: 1, csapatMeret: 13, sportag: "vizilabda", versenyszam: "ferfi_csapat" },
    { helyezes: 2, csapatMeret: 1, sportag: "ottusa", versenyszam: "ottusa_egyeni" },
    { helyezes: 2, csapatMeret: 1, sportag: "vivas", versenyszam: "torvivas_egyeni" },
    { helyezes: 2, csapatMeret: 1, sportag: "vivas", versenyszam: "kardvivas_egyeni" },
    { helyezes: 2, csapatMeret: 1, sportag: "sportloveszet", versenyszam: "onmukodo_sportpisztoly" },
    { helyezes: 2, csapatMeret: 1, sportag: "uszas", versenyszam: "400m_gyorsuszas" },
    { helyezes: 2, csapatMeret: 1, sportag: "uszas", versenyszam: "200m_melluszas" },
    { helyezes: 2, csapatMeret: 1, sportag: "kajakkenu", versenyszam: "kenu_egyes_10000m" },
    { helyezes: 2, csapatMeret: 1, sportag: "kajakkenu", versenyszam: "kajak_egyes_1000m" },
    { helyezes: 2, csapatMeret: 1, sportag: "birkozas", versenyszam: "kotott_fogas_pehelysuly" },
    { helyezes: 2, csapatMeret: 8, sportag: "torna", versenyszam: "noi_osszetett_csapat" },
    { helyezes: 3, csapatMeret: 1, sportag: "sportloveszet", versenyszam: "sportpisztoly" },
    { helyezes: 3, csapatMeret: 1, sportag: "vivas", versenyszam: "kardvivas_egyeni" },
    { helyezes: 3, csapatMeret: 1, sportag: "atletika", versenyszam: "tavolugras" },
    { helyezes: 3, csapatMeret: 1, sportag: "birkozas", versenyszam: "szabad_fogas_kozepsuly" },
    { helyezes: 3, csapatMeret: 1, sportag: "torna", versenyszam: "felemas_korlat" },
    { helyezes: 3, csapatMeret: 1, sportag: "torna", versenyszam: "osszetett_egyeni" },
    { helyezes: 3, csapatMeret: 1, sportag: "torna", versenyszam: "gerenda" },
    { helyezes: 3, csapatMeret: 1, sportag: "torna", versenyszam: "talajtorna" },
    { helyezes: 3, csapatMeret: 1, sportag: "atletika", versenyszam: "kalapacsvetes" },
    { helyezes: 3, csapatMeret: 1, sportag: "atletika", versenyszam: "50km_gyaloglas" },
    { helyezes: 3, csapatMeret: 1, sportag: "ottusa", versenyszam: "ottusa_egyeni" },
    { helyezes: 3, csapatMeret: 1, sportag: "uszas", versenyszam: "100m_gyorsuszas" },
    { helyezes: 3, csapatMeret: 4, sportag: "atletika", versenyszam: "4x100m_valtofutas" },
    { helyezes: 3, csapatMeret: 2, sportag: "kajakkenu", versenyszam: "kenu_kettes_10000m" },
    { helyezes: 3, csapatMeret: 8, sportag: "torna", versenyszam: "keziszer_csapat" },
    { helyezes: 3, csapatMeret: 6, sportag: "vivas", versenyszam: "torvivas_csapat" },
    { helyezes: 4, csapatMeret: 1, sportag: "torna", versenyszam: "gerenda" },
    { helyezes: 4, csapatMeret: 1, sportag: "uszas", versenyszam: "200m_mell" },
    { helyezes: 4, csapatMeret: 1, sportag: "birkozas", versenyszam: "kotottfogas_felnehezsuly" },
    { helyezes: 4, csapatMeret: 1, sportag: "torna", versenyszam: "talaj" },
    { helyezes: 4, csapatMeret: 1, sportag: "birkozas", versenyszam: "kotottfogas_kozepsuly" },
    { helyezes: 4, csapatMeret: 1, sportag: "birkozas", versenyszam: "kotottfogas_konnyusuly" },
    { helyezes: 5, csapatMeret: 1, sportag: "okolvivas", versenyszam: "pehelysuly" },
    { helyezes: 5, csapatMeret: 1, sportag: "okolvivas", versenyszam: "konnyusuly" },
    { helyezes: 5, csapatMeret: 1, sportag: "uszas", versenyszam: "100m_gyors" },
    { helyezes: 5, csapatMeret: 1, sportag: "atletika", versenyszam: "diszkoszvetes" },
    { helyezes: 5, csapatMeret: 1, sportag: "vivas", versenyszam: "parbajtor_egyeni" },
    { helyezes: 5, csapatMeret: 2, sportag: "kajak kenu", versenyszam: "kenu_kettes_1000m" },
    { helyezes: 5, csapatMeret: 2, sportag: "kerekparozas", versenyszam: "ketuleses_verseny" },
    { helyezes: 5, csapatMeret: 4, sportag: "uszas", versenyszam: "4 200m_gyorsvalto" },
    { helyezes: 5, csapatMeret: 5, sportag: "vivas", versenyszam: "parbajtor_csapat" },
    { helyezes: 6, csapatMeret: 1, sportag: "birkozas", versenyszam: "kotottfogas_legsuly" },
    { helyezes: 6, csapatMeret: 1, sportag: "kajak kenu", versenyszam: "kajak_egyes_500m" },
    { helyezes: 6, csapatMeret: 1, sportag: "torna", versenyszam: "osszetett_egyeni" },
    { helyezes: 6, csapatMeret: 1, sportag: "kerekparozas", versenyszam: "repuloverseny" },
    { helyezes: 6, csapatMeret: 1, sportag: "uszas", versenyszam: "400m_gyors" },
    { helyezes: 6, csapatMeret: 1, sportag: "torna", versenyszam: "felemaskorlat" },
    { helyezes: 6, csapatMeret: 8, sportag: "torna", versenyszam: "osszetett_csapat" },
];